### ISSUE TITLE
Team member contributions

### ISSUE THREAD

**Issue by bisraelsen** [PostRockRaven/Bomark_CSCI2270_FinalProject#1]
I am trying to see how/what each team member contributed. I can only see one person who committed. Can you help me with this?

**Comment by PostRockRaven** [comment]
BrantonDemoss and outstretchedPupil helped me with the project. However, we had confusion over the whole pushing and pulling thing, and outstretchedPupil forked the empty project to his repo somehow. I am unsure how to make it show all the info though. But I made the data structure and class and everything because I wanted a vector of genres being the heads of pointers to doubly linked lists. And then I made a good chunk of the functions for reading in the text file, creating the text file. brantonDemoss and outstretchedPupil helped with splitting the rest of the functions and helping me edit them to get rid of bugs. They should each have the full project in their final repo, outstretchedPupil has a fork to my TruePatricianMusic repository. That repository was the one where we added everything because I put it in the wrong name, but the contributions for both my team members should be visible here: https://github.com/PostRockRaven/TruePatricianMusic (*but this is not the finished project, the one here is, bit this one still works and is complete expect for comments and such*)

**Comment by bisraelsen** [comment]
You were all meant to commit to the same repo. I will do my best to sort this out.

BTW on the other page it also said adam tamariello is on the team too...

**Comment by PostRockRaven** [comment]
Adam ended up doing his own project by himself because he was out of town. I should change that. But on that page it should have the forks to everyone else's contribution.

**Comment by bisraelsen** [comment]
thanks!
